### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by apberr-adobe** [ma2gedev/breadcrumble_ex#15]
The latest version on hex.pm is very outdated, from 2017.  Since there are many new changes, including silencing compiler warnings, could you please bump the version so those changes will be accessible through mix?

**Comment by ma2gedev** [comment]
@apberr-adobe Thank you for your feedback. 👍  I just published latest version to hex. 

https://hex.pm/packages/breadcrumble/1.0.5

Is this solve problems you facing? If the problem persists, could you please provide more information. 😄

**Comment by apberr-adobe** [comment]
Thank you so much!
