### ISSUE TITLE
another compilation warning

### ISSUE THREAD

**Issue by stephenmoloney** [ma2gedev/breadcrumble_ex#7]
`warning: variable "breadcrumb_text" does not exist and is being expanded to "breadcrumb_text()", please use parentheses to remove the ambiguity or change the variable name
  lib/mix/tasks/breadcrumble.gen.views.ex:14`

**Comment by ma2gedev** [comment]
Thank you for reporting. I fixed on https://github.com/ma2gedev/breadcrumble_ex/commit/0cde66806a4c80ee47a5fa152356b3546f68d1f0 .

**Comment by stephenmoloney** [comment]
:+1:
