### ISSUE TITLE
Pass parameter into plug for previous plug parameter

### ISSUE THREAD

**Issue by cdesch** [ma2gedev/breadcrumble_ex#9]
This may not be a Breadcrumble question, but how do I pass a parameter from a previous plug into the breadcrumbable? For example, if the previous plug `set_merchant` sets the merchant on `conn.params.merchant`, how can I pass that `id` to breadcrumable?

       plug :set_merchant
       plug :add_breadcrumb, name: "Dashboard", url: "/dashboard/#{conn.params.merchant_id}"

.....
```
 defp set_merchant(conn, _opt) do
    case conn.params do
      %{"merchant_id" => merchant_id} ->
        case MyApp.find_merchant(merchant_id) do
          nil ->
            conn |> redirect(to: "/dashboard/#{merchant_id}") |> halt
          merchant ->
            assign(conn, :merchant, merchant)
        end
      _ ->
        conn |> redirect(to: "/") |> halt
    end
  end
```

**Comment by stephenmoloney** [comment]
I would see two options here, something like below:

1. Run the plug in the controller directly... ie...
```
defmodule DashboardController do
  def index(conn, params) do
    add_breadcrumb(conn, name: "Dashboard", url: "/dashboard/#{conn.params.merchant_id}")
  end
end
```

or 

2. Create a custom plug which calls the add_breadcrumb plug
```
def add_dashboard_plug(conn, _opts) do
  add_breadcrumb(conn, name: "Dashboard", url: "/dashboard/#{conn.params.merchant_id}")
end

defmodule DashboardController do
  plug :add_dashboard_plug
end
```

[updated on 6/01/2018, making it clearer]

**Comment by ma2gedev** [comment]
Thank you @stephenmoloney !

**Comment by cdesch** [comment]
That works! Thanks!

**Comment by stephenmoloney** [comment]
sure thing, @cdesch , I updated it a little to show all the detail just now...
